export enum LegalStatus {
  INDIVIDUAL_ENTERPRISE = 'Individual Enterprise',
  GENERAL_PARTNERSHIP = 'General Partnership',
  LIMITED_LIABILITY_COMPANY = 'Limited Liability Company',
  PUBLIC_COMPANY = 'Public Company',
  COOPERATIVE = 'Cooperative',
  SOCIAL_ENTERPRISE = 'Social Enterprise',
  STARTUP = 'Startup',
  FAMILY_BUSINESS = 'Family Business',
  SOLE_PROPRIETORSHIP = 'Sole Proprietorship',
  PARTNERSHIP = 'Partnership',
  CORPORATION = 'Corporation',
  LIMITED_PARTNERSHIP = 'Limited Partnership',
  MICRO_ENTERPRISE = 'Micro-Enterprise',
  ASSOCIATION = 'Association',
}

export enum Sector {
  BAKERY = 'Bakery',
  FOOD_INDUSTRY = 'Food Industry',
  HOSPITALITY = 'Hospitality',
  RETAIL = 'Retail',
  SMALL_BUSINESS = 'Small Business',
  CATERING = 'Catering',
  DISTRIBUTION = 'Distribution',
  WHOLESALE = 'Wholesale',
  ARTISANAL = 'Artisanal',
  SPECIALTY_FOOD = 'Specialty Food',
  CAFÉ = 'Café',
  PASTRY_SHOP = 'Pastry Shop',
  CONFECTIONERY = 'Confectionery',
  ORGANIC_FOOD = 'Organic Food',
  LOCAL_PRODUCE = 'Local Produce',
  ONLINE_RETAIL = 'Online Retail',
  EXPORT_IMPORT = 'Export/Import',
  CULINARY_EDUCATION = 'Culinary Education',
  EVENT_PLANNING = 'Event Planning',
  FRANCHISE = 'Franchise',
  OTHER = 'Other',
}
